### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kanishk951**
Ha Ha

### CODE REVIEW

**Comment by Dirvann** [comment]
love this feature

**Review by Kanishk951 — COMMENTED** [review]
Cool

**Comment by mandar1jn** [comment]
If dani would actually check his github I think he will enjoy this.

**Comment by mandar1jn** [comment]
If dani would actually check his github I think he will enjoy this.

**Comment by mandar1jn** [comment]
If dani would actually check his github I think he will enjoy this.

**Comment by mandar1jn** [comment]
If dani would actually check his github I think he will enjoy this.

**Review by mandar1jn — APPROVED** [review]
Good

**Review by josephAttia — APPROVED** [review]
Amazing

**Comment by schwarzsky** [comment]
KEKW

**Comment by tehrelt** [comment]
_Excellent_

**Comment by vinyashegde** [comment]
Yoo you all here!!!

**Comment by BeansBeefBroccoli** [comment]
That isn't even how markdown works though. Comments don't exist.

**Comment by mandar1jn** [comment]
> That isn't even how markdown works though. Comments don't exist.

I don’t think anybody cares. Not like dani ever checks herr

**Review by proJM-Coding — APPROVED** [review]
Very cool

**Comment by ghost** [comment]
@DaniDevy Is your github dead?

**Comment by vinyashegde** [comment]
i guess its dead! and his channel tooo!🙂

**Comment by ghost** [comment]
r/DaniDead

**Comment by ghost** [comment]
Did anyone notice this repo: [https://github.com/jdgbas/he](https://github.com/jdgbas/he). It's the same repo as this one but it's not a fork and it's made by @jdgbas. I don't think there is any difference between the 2 repos

**Comment by BeansBeefBroccoli** [comment]
Never noticed it, that's real strange

**Comment by ghost** [comment]
Are @DaniDevy and @jdgbas the same people?

**Comment by ghost** [comment]
Dani is the only person who has done a commit to the repo. Not even the owner.

**Comment by hmm-monke** [comment]
why

**Comment by ghost** [comment]
I just want to know about the link. Dani and him seem connected or the same person

**Pull request closed without merging**
